name: buildnote PR

on:
  pull_request:
    paths:
      - '*.kts'
      - '/**'
      - '.github/workflows/pr.yml'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Gradle check
        run: ./gradlew check
