on:
  push:
    tags:
      - '*'
jobs:
  release_publish:
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      NEXUS_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.REPOSITORY_PIPELINE_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Publish to GitHub
        run: ./gradlew githubRelease

      - name: Publish to Maven Central Staging
        run: ./gradlew publishMavenJavaPublicationToSonatypeStagingRepository

      - name: Publish to Maven Central Release
        run: ./gradlew closeAndReleaseRepository
