on:
  push:
    tags:
      - '*'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  release_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Grab tag name
        uses: olegtarasov/get-tag@v2
        id: tagName

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Publish to Bintray
        run: ./scripts/release-publish-bintray.sh
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

      - name: Publish to GitHub
        run: ./scripts/release-publish-github.sh
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_PIPELINE_GITHUB_TOKEN }}

      - name: Publish to Maven Central Staging
        run: ./scripts/release-publish-maven-central-staging.sh
        env:
          SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          NEXUS_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
