on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version (e.g: 1.0.0.0)'
        required: true
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Create release ${{ github.event.release_version }}
        run: ./scripts/release.sh "${{ github.event.release_version }}"
